server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb:http://CLOUD-PAYMENT-SERVICE          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb:http://CLOUD-PAYMENT-SERVICE
          filters:
          - AddRequestHeader=X-Request-red, blue
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
#            - Cookie=username,vent

        - id: payment_routh3 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb:http://CLOUD-PAYMENT-SERVICE         #匹配后提供服务的路由地址
          filters:
            - AddRequestHeader=NewHeader, Bar
            - AddRequestParameter=NewParam, Param
          predicates:
            - Path=/testfilter      # 断言，路径相匹配的进行路由
            - After=2022-10-31T10:59:20.694+08:00[Asia/Shanghai]
#            - Cookie=username,vent


eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
